## Ex:2 Data Wrangling and Transformation 
### Objective

To perform data wrangling and transformation on a dataset using Python and Pandas by handling missing values, removing duplicates, correcting data types, filtering data, and transforming variables into a suitable format for data analysis and machine learning.



##  Dataset Description

The dataset contains information about **student academic performance, educational background, MBA specialization, and placement salary**.

###  Dataset Attributes

| Column | Description |
|:---|:---|
| `sl_no` | Serial number / student identifier |
| `gender` | Gender of the student |
| `hsc_p` | Higher Secondary / 12th percentage |
| `hsc_s` | Higher Secondary stream |
| `degree_p` | Undergraduate degree percentage |
| `degree_t` | Undergraduate degree type |
| `etest_p` | Employability / entrance test percentage |
| `specialisation` | MBA specialization |
| `mba_p` | MBA percentage |
| `salary` | Salary offered after placement |

---

## Experiment Question

 **Using the given student placement dataset, perform data wrangling and transformation by handling missing values, scaling numerical features, detecting and treating outliers, encoding categorical variables, and generating a final model-ready dataset.**

Data wrangling and transformation is the process of converting raw student placement data into a clean, consistent, and machine-learning-ready dataset. In this experiment, the given student placement dataset is first loaded into a Pandas DataFrame and explored by examining its rows, columns, data types, and descriptive statistics. Missing values are then identified and handled by removing records with missing `salary` values and replacing missing values in `hsc_p`, `degree_p`, and `etest_p` with their respective mean values. The numerical attributes such as `hsc_p`, `degree_p`, `etest_p`, and `salary` are transformed using feature-scaling techniques such as `StandardScaler` and `MinMaxScaler` to bring the variables into suitable numerical ranges. The dataset is then divided into input features (`X`) and the target variable (`Y`), where `salary` is considered the target. The preprocessed data is saved as `Pre.csv` for further processing. Next, possible outliers in the `salary` attribute are identified using a boxplot and statistically detected using the Z-score method, where values with an absolute Z-score greater than 3 are considered potential outliers. Outliers are also treated using the capping and flooring method by calculating the 5th and 95th percentiles and replacing values outside these limits with the corresponding boundary values. The salary distribution before and after outlier treatment is then compared using visualization. Since the dataset also contains categorical attributes such as `gender`, `hsc_s`, `degree_t`, and `specialisation`, these variables are converted into numerical representations using `LabelEncoder` and One-Hot Encoding. Finally, the completely transformed dataset is verified for missing values, data types, dimensions, and numerical representation, and the resulting model-ready dataset is saved as `Final.csv`. Thus, the experiment demonstrates the complete workflow of preparing real-world tabular data for data analysis and machine-learning applications.

## Step 1: Start by importing the necessary Python libraries for data preprocessing.

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from scipy.stats import zscore
from scipy import stats
from sklearn.preprocessing import LabelEncoder

## Step 2: Load the placement dataset into a Pandas Dataframe.

In [4]:

df=pd.read_csv("data.csv")
df.info()
df.shape
df.head()
df.tail()
df.sample(5)
df.describe()
df.loc[0]
df.iloc[0]
df[0:2]
df["degree_p"]
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   hsc_p           210 non-null    float64
 3   hsc_s           215 non-null    str
 4   degree_p        213 non-null    float64
 5   degree_t        215 non-null    str
 6   etest_p         211 non-null    float64
 7   specialisation  215 non-null    str
 8   mba_p           214 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 16.9 KB

sl_no              0
gender             0
hsc_p              5
hsc_s              0
degree_p           2
degree_t           0
etest_p            4
specialisation     0
mba_p              1
salary            67
dtype: int64

## Step 3:Take a quick look at the data to understand its structure and identify any missing values or anomalies.

#### The method isnull() checks each element in the DataFrame (or Series) to see if it is NaN (Not a Number) or None (missing value).
It returns a DataFrame (or Series) of the same shape as the input, with Boolean values:
#### True: The value is null (NaN or None).
#### False: The value is not null.

## Step 4: Handle Missing Data
### Option 1: If the dataset is large and only a small percentage of data is missing, you can remove rows with missing values using dropna(subset,inplace)

In [5]:
df.dropna(subset=["salary"],inplace = True)
df.isnull().sum()

sl_no             0
gender            0
hsc_p             2
hsc_s             0
degree_p          1
degree_t          0
etest_p           2
specialisation    0
mba_p             0
salary            0
dtype: int64

### Option 2:If removing data isn't ideal, you can impute (df.[""].fillna(df[""].mean(),inplace)) missing values using methods like mean, median, or most frequent.

In [6]:
df["hsc_p"]=df["hsc_p"].fillna(df["hsc_p"].mean())
df["degree_p"]=df["degree_p"].fillna(df["degree_p"].mean())
df["etest_p"]=df["etest_p"].fillna(df["etest_p"].mean())
df.isnull().sum()

sl_no             0
gender            0
hsc_p             0
hsc_s             0
degree_p          0
degree_t          0
etest_p           0
specialisation    0
mba_p             0
salary            0
dtype: int64

## Step 5: Feature Scaling
Feature scaling is the process of converting numerical features to a similar scale so that one feature does not dominate another simply because it has larger numerical values.

<img src="https://i.postimg.cc/G21gMYnF/f.png" alt="Image Description" width="500">









## Option 1( StandardScaler): This method scales the data to have a mean of 0 and a standard deviation of 1.

In [7]:
c=["hsc_p","degree_p","etest_p","salary"]
s1 = StandardScaler()
df[c]=s1.fit_transform(df[c])
df.head()

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,M,2.265997e+00,Commerce,-1.652293,Sci&Tech,-1.328518,Mkt&HR,58.80,-0.200292
1,2,M,8.987875e-01,Science,1.346845,Sci&Tech,0.978332,Mkt&Fin,66.28,-0.951839
2,3,M,1.533482e-15,Arts,-0.728534,Comm&Mgmt,0.136149,Mkt&Fin,57.80,-0.415019
4,5,M,3.883770e-01,Commerce,0.703293,Comm&Mgmt,1.732635,Mkt&Fin,55.50,1.463849
7,8,M,-6.475513e-01,Science,-0.420614,Sci&Tech,-0.449718,Mkt&Fin,62.14,-0.393547

#### Option 2:This method scales the data to a fixed range, usually between 0 and 1. 
###  MinMaxScaler()

In [8]:
s2=MinMaxScaler()
df[c]=s2.fit_transform(df[c])
df.head()

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,M,0.857051,Commerce,0.057143,Sci&Tech,0.104167,Mkt&HR,58.80,0.094595
1,2,M,0.586729,Science,0.613714,Sci&Tech,0.760417,Mkt&Fin,66.28,0.000000
2,3,M,0.409023,Arts,0.228571,Comm&Mgmt,0.520833,Mkt&Fin,57.80,0.067568
4,5,M,0.485812,Commerce,0.494286,Comm&Mgmt,0.975000,Mkt&Fin,55.50,0.304054
7,8,M,0.280990,Science,0.285714,Sci&Tech,0.354167,Mkt&Fin,62.14,0.070270

## Step 6  Option 1: Identifying Outliers Using Z-Scores
The value of 3 in the context of Z-scores is often used as a threshold to identify outliers in a dataset. A Z-score represents how many standard deviations a data point is away from the mean of the dataset. Specifically:

A Z-score of 0 means the data point is exactly at the mean.
A Z-score of 1 means the data point is one standard deviation above the mean, and so on.
A Z-score of 3 corresponds to a data point being 3 standard deviations away from the mean. For a normal distribution, about 99.7% of the data points fall within 3 standard deviations of the mean (according to the 68-95-99.7 rule, which describes the spread of data in a normal distribution). Therefore, points with Z-scores greater than 3 or less than -3 are considered unusually far from the mean and are often flagged as outliers.

This threshold (Z > 3 or Z < -3) is commonly used in many statistical applications because it captures the extreme values that are rare in a normal distribution, which are typically considered to be outliers. However, the choice of threshold can vary depending on the specific application and the nature of the data.

[![Chat-GPT-Image-Aug-20-2026-08-06-05-PM.png](https://i.postimg.cc/2SFTtcXL/Chat-GPT-Image-Aug-20-2026-08-06-05-PM.png)](https://postimg.cc/4Yyz75GX)

In [16]:
columns_to_check=["salary"]
z_score=stats.zscore(df[columns_to_check])
u=(z_score>3)
l=(z_score<-3)
indx = u | l
clean_df=df[~indx]
df.info()
clean_df.info()

<class 'pandas.DataFrame'>
Index: 148 entries, 0 to 213
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           148 non-null    int64
 1   gender          148 non-null    str
 2   hsc_p           148 non-null    float64
 3   hsc_s           148 non-null    str
 4   degree_p        148 non-null    float64
 5   degree_t        148 non-null    str
 6   etest_p         148 non-null    float64
 7   specialisation  148 non-null    str
 8   mba_p           148 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 12.7 KB
<class 'pandas.DataFrame'>
Index: 145 entries, 0 to 213
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           145 non-null    int64
 1   gender          145 non-null    str
 2   hsc_p           145 non-null    float64
 3   hsc_s           145 non-null    str
 4   degree_p        145 non-null    float64
 5   degree_t        145 non-null    str
 6   etest_p         145 non-null    float64
 7   specialisation  145 non-null    str
 8   mba_p           145 non-null    float64
 9   salary          145 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 12.5 KB

### Option 2:  Capping and Flooring Outliers
Capping and flooring is an outlier-treatment technique where extreme values are replaced with predefined boundary values instead of deleting the records.

In [18]:
l1=df["salary"].quantile(0.05)
u1=df["salary"].quantile(0.95)
df_capped=df.copy()
df_capped["salary"]=df_capped["salary"].clip(l1,u1)
df_capped.info()
df.head()

<class 'pandas.DataFrame'>
Index: 148 entries, 0 to 213
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           148 non-null    int64
 1   gender          148 non-null    str
 2   hsc_p           148 non-null    float64
 3   hsc_s           148 non-null    str
 4   degree_p        148 non-null    float64
 5   degree_t        148 non-null    str
 6   etest_p         148 non-null    float64
 7   specialisation  148 non-null    str
 8   mba_p           148 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 12.7 KB

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,M,0.857051,Commerce,0.057143,Sci&Tech,0.104167,Mkt&HR,58.80,0.094595
1,2,M,0.586729,Science,0.613714,Sci&Tech,0.760417,Mkt&Fin,66.28,0.000000
2,3,M,0.409023,Arts,0.228571,Comm&Mgmt,0.520833,Mkt&Fin,57.80,0.067568
4,5,M,0.485812,Commerce,0.494286,Comm&Mgmt,0.975000,Mkt&Fin,55.50,0.304054
7,8,M,0.280990,Science,0.285714,Sci&Tech,0.354167,Mkt&Fin,62.14,0.070270

## Step 7: Convert categorical variables into numerical format using LabelEncoder ().
[![Picture1.png](https://i.postimg.cc/yNpNvnVd/Picture1.png)](https://postimg.cc/zLW5fCHZ)

## Convert categorical variables into numerical format using one hot encoder

[![Picture2.png](https://i.postimg.cc/gcZ0Hv1J/Picture2.png)](https://postimg.cc/HjTHp7YD)

In [19]:

L1=LabelEncoder()
df["gender"]=L1.fit_transform(df["gender"])
df["hsc_s"]=L1.fit_transform(df["hsc_s"])
df["degree_t"]=L1.fit_transform(df["degree_t"])
df["specialisation"]=L1.fit_transform(df["specialisation"])
df.head()

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,1,0.857051,1,0.057143,2,0.104167,1,58.80,0.094595
1,2,1,0.586729,2,0.613714,2,0.760417,0,66.28,0.000000
2,3,1,0.409023,0,0.228571,0,0.520833,0,57.80,0.067568
4,5,1,0.485812,1,0.494286,0,0.975000,0,55.50,0.304054
7,8,1,0.280990,2,0.285714,2,0.354167,0,62.14,0.070270

In [26]:
c=["gender"]
one_hot_encoded_data=pd.get_dummies(df,columns=c)
one_hot_encoded_data.to_csv('clean.csv',index=False)

Y=df['salary'].copy()
X=df.drop(columns=['salary','sl_no']).copy()
one_hot_encoded_data.head()

,sl_no,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary,gender_0,gender_1
0,1,0.857051,1,0.057143,2,0.104167,1,58.80,0.094595,False,True
1,2,0.586729,2,0.613714,2,0.760417,0,66.28,0.000000,False,True
2,3,0.409023,0,0.228571,0,0.520833,0,57.80,0.067568,False,True
4,5,0.485812,1,0.494286,0,0.975000,0,55.50,0.304054,False,True
7,8,0.280990,2,0.285714,2,0.354167,0,62.14,0.070270,False,True

# Exercise: Data Cleaning and Transformation – Automobile Dataset

## Step 1: Load and Explore the Dataset

### 1. Load the Dataset
- Import Pandas and load the Automobile dataset.
- Display the first 10 rows.
- Display the shape of the dataset.

### 2. Explore the Dataset
- Display the column names.
- Display the data types.
- Generate descriptive statistics.
- Identify numerical and categorical columns.
- Display unique values in categorical columns.

## Step 2: Data Cleaning

### 3. Check Missing Values
- Check for missing values in each column.
- Display the number and percentage of missing values.

### 4. Handle Missing Values
- Replace missing numerical values using mean or median.
- Replace missing categorical values using mode.
- Verify that no missing values remain.

### 5. Remove Duplicate Records
- Check for duplicate rows.
- Display the number of duplicate records.
- Remove duplicate records.
- Verify the result.

### 6. Clean the `horsepower` Column
- Identify non-numeric values such as `?`.
- Replace `?` with `NaN`.
- Convert `horsepower` to numeric.
- Handle the resulting missing values.

## Step 3: Data Transformation

### 7. Transform the `origin` Column
- Display the unique values in `origin`.
- Convert the values into meaningful labels:
  - `1` → `usa`
  - `2` → `europe`
  - `3` → `japan`

### 8. Create `weight_kg`
- Create a new column `weight_kg`.
- Convert weight from pounds to kilograms.

  `weight_kg = weight × 0.453592`

### 9. Create `mpg_category`
Create a new column based on `mpg`:
- `< 20` → `Low`
- `20–29` → `Medium`
- `≥ 30` → `High`

### 10. Create `vehicle_age`
- Create a new column `vehicle_age`.
- Assume the current year is 2026.

  `vehicle_age = 2026 - model_year`

### 11. Rename Columns
Rename:
- `mpg` → `miles_per_gallon`
- `horsepower` → `hp`
- `weight` → `weight_lbs`
- `model_year` → `year`

### 12. Filter the Data
Display vehicles:
- With `mpg > 30`
- With `horsepower > 150`
- With `cylinders >= 6`
- Manufactured after 1980
- Originating from `usa`

## Step 4: Encoding Categorical Data

### 13. Label Encoding
- Apply `LabelEncoder` to the `origin` column.
- Create a new column `origin_encoded`.
- Display the original and encoded values.
- Display the category-to-label mapping.

### 14. One-Hot Encoding
- Apply One-Hot Encoding to the `origin` column.
- Compare Label Encoding and One-Hot Encoding.
- Which encoding method is more appropriate for `origin`? Explain why.

## Step 5: Outlier Detection

### 15. Identify Outliers Using Z-Scores
- Calculate the Z-score for the numerical features.
- Identify observations with `|Z-score| > 3` as outliers.
- Count the outliers in each numerical column.
- Display the rows containing outliers.
- Decide whether the outliers should be removed or retained.

## Step 6: Feature Scaling

### 16. Standardization Using StandardScaler
- Select the numerical features.
- Apply `StandardScaler`.
- Display the standardized values.
- Verify that the features have approximately mean `0` and standard deviation `1`.

## Step 7: Normalization

### 17. Normalization Using MinMaxScaler
- Apply `MinMaxScaler` to the numerical features.
- Transform the features to the range `[0, 1]`.
- Display the normalized values.
- Compare **Standardization** and **Normalization**.
- Explain when each scaling method is appropriate.

## Step 8: Create Features and Target

### 18. Create X and Y Variables
- Select the appropriate input features as **X (independent variables)**.
- Select `mpg` as **Y (target variable)**.
- Display the shape of `X` and `Y`.
- Save `X` and `Y` into `automobile_X_Y.csv`.
- Load the CSV file again and display the first 5 rows.

## Step 9: Save the Final Dataset

### 19. Save the Preprocessed Dataset
- Combine the processed features and target variable.
- Display the final dataset.
- Check for missing values.
- Save the final dataset as `automobile_preprocessed.csv`.

In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("Automobile.csv")
df.head(10)

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8.0,307.0,130.0,3504.0,12.0,70,usa
1,buick skylark 320,15.0,8.0,350.0,165.0,3693.0,11.5,70,usa
2,plymouth satellite,18.0,8.0,318.0,150.0,3436.0,11.0,70,usa
3,amc rebel sst,16.0,8.0,304.0,150.0,3433.0,12.0,70,usa
4,ford torino,17.0,NaN,302.0,140.0,3449.0,10.5,70,usa
5,ford galaxie 500,15.0,8.0,429.0,198.0,4341.0,10.0,70,usa
6,chevrolet impala,14.0,8.0,454.0,220.0,NaN,9.0,70,usa
7,plymouth fury iii,14.0,8.0,440.0,215.0,4312.0,8.5,70,usa
8,pontiac catalina,14.0,8.0,455.0,NaN,4425.0,10.0,70,usa
9,amc ambassador dpl,15.0,8.0,390.0,190.0,3850.0,8.5,70,usa

In [7]:
df.shape

(398, 9)

In [8]:
df.columns

Index(['name', 'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin'],
      dtype='str')

In [9]:
df.dtypes

name                str
mpg             float64
cylinders       float64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin              str
dtype: object

In [10]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,395.000000,395.000000,386.000000,396.000000,395.000000,398.000000
mean,23.514573,5.445570,193.340506,104.316062,2965.025253,15.562278,76.010050
std,7.815984,1.696203,104.425993,38.086281,845.254458,2.750260,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,102.500000,75.250000,2222.250000,13.850000,73.000000
50%,23.000000,4.000000,146.000000,92.500000,2797.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,125.000000,3581.750000,17.150000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [11]:
numerical_columns = df.select_dtypes(include=np.number).columns
print(numerical_columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year'],
      dtype='str')

In [13]:
categorical_columns = df.select_dtypes(include="str").columns
print(categorical_columns)

Index(['name', 'origin'], dtype='str')

In [14]:
for col in categorical_columns:
    print(col)
    print(df[col].unique())
    print()

name
<StringArray>
[ 'chevrolet chevelle malibu',          'buick skylark 320',
         'plymouth satellite',              'amc rebel sst',
                'ford torino',           'ford galaxie 500',
           'chevrolet impala',          'plymouth fury iii',
           'pontiac catalina',         'amc ambassador dpl',
 ...
 'chrysler lebaron medallion',             'ford granada l',
           'toyota celica gt',          'dodge charger 2.2',
           'chevrolet camaro',            'ford mustang gl',
                  'vw pickup',              'dodge rampage',
                'ford ranger',                 'chevy s-10']
Length: 305, dtype: str

origin
<StringArray>
['usa', 'japan', 'europe']
Length: 3, dtype: str

In [15]:
df.isnull().sum()

name             0
mpg              0
cylinders        3
displacement     3
horsepower      12
weight           2
acceleration     3
model_year       0
origin           0
dtype: int64

In [16]:
df["horsepower"].value_counts()

horsepower
150.0    22
90.0     20
88.0     19
110.0    17
100.0    16
         ..
77.0      1
132.0     1
64.0      1
116.0     1
82.0      1
Name: count, Length: 93, dtype: int64

In [17]:
missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percentage": missing_percentage
})

missing_table

              Missing Count  Missing Percentage
name                      0            0.000000
mpg                       0            0.000000
cylinders                 3            0.753769
displacement              3            0.753769
horsepower               12            3.015075
weight                    2            0.502513
acceleration              3            0.753769
model_year                0            0.000000
origin                    0            0.000000

In [18]:
df["horsepower"] = df["horsepower"].replace("?", np.nan)

In [19]:
df["horsepower"] = pd.to_numeric(df["horsepower"])

In [20]:
df.isnull().sum()

name             0
mpg              0
cylinders        3
displacement     3
horsepower      12
weight           2
acceleration     3
model_year       0
origin           0
dtype: int64

In [21]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mean())

In [22]:
df.isnull().sum()

name            0
mpg             0
cylinders       3
displacement    3
horsepower      0
weight          2
acceleration    3
model_year      0
origin          0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df = df.drop_duplicates()

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df["horsepower"] = df["horsepower"].replace("?", np.nan)
df["horsepower"] = pd.to_numeric(df["horsepower"])
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mean())

In [27]:
df["horsepower"].dtype

dtype('float64')

In [28]:
df["origin"].unique()

<StringArray>
['usa', 'japan', 'europe']
Length: 3, dtype: str

In [29]:
origin_mapping = {
    1: "usa",
    2: "europe",
    3: "japan",
    "1": "usa",
    "2": "europe",
    "3": "japan"
}

df["origin"] = df["origin"].replace(origin_mapping)

In [30]:
df["origin"].unique()

<StringArray>
['usa', 'japan', 'europe']
Length: 3, dtype: str

In [31]:
df["weight_kg"] = df["weight"] * 0.453592

In [32]:
df[["weight", "weight_kg"]].head()

   weight    weight_kg
0  3504.0  1589.386368
1  3693.0  1675.115256
2  3436.0  1558.542112
3  3433.0  1557.181336
4  3449.0  1564.438808

In [33]:
def mpg_category(mpg):
    if mpg < 20:
        return "Low"
    elif mpg < 30:
        return "Medium"
    else:
        return "High"

In [34]:
df["mpg_category"] = df["mpg"].apply(mpg_category)

In [35]:
df[["mpg", "mpg_category"]].head(10)

    mpg mpg_category
0  18.0          Low
1  15.0          Low
2  18.0          Low
3  16.0          Low
4  17.0          Low
5  15.0          Low
6  14.0          Low
7  14.0          Low
8  14.0          Low
9  15.0          Low

In [36]:
df["year"] = df["model_year"] + 1900

In [37]:
df["vehicle_age"] = 2026 - df["year"]

In [38]:
df[["model_year", "year", "vehicle_age"]].head()

   model_year  year  vehicle_age
0          70  1970           56
1          70  1970           56
2          70  1970           56
3          70  1970           56
4          70  1970           56

In [39]:
df = df.rename(columns={
    "mpg": "miles_per_gallon",
    "horsepower": "hp",
    "weight": "weight_lbs",
    "model_year": "year"
})

In [40]:
df.columns

Index(['name', 'miles_per_gallon', 'cylinders', 'displacement', 'hp',
       'weight_lbs', 'acceleration', 'year', 'origin', 'weight_kg',
       'mpg_category', 'year', 'vehicle_age'],
      dtype='str')

In [42]:

df = df.reset_index(drop=True)
df = df.loc[:, ~df.columns.duplicated()]


df["origin"] = df["origin"].astype(str).str.lower()

print(df.columns)

Index(['name', 'miles_per_gallon', 'cylinders', 'displacement', 'hp',
       'weight_lbs', 'acceleration', 'year', 'origin', 'weight_kg',
       'mpg_category', 'vehicle_age'],
      dtype='str')

In [43]:
filtered_df = df[
    (df["miles_per_gallon"] > 30) &
    (df["hp"] > 150) &
    (df["cylinders"] >= 6) &
    (df["year"] > 1980) &
    (df["origin"] == "usa")
]

filtered_df

Empty DataFrame
Columns: [name, miles_per_gallon, cylinders, displacement, hp, weight_lbs, acceleration, year, origin, weight_kg, mpg_category, vehicle_age]
Index: []

In [44]:
print("Number of vehicles:", len(filtered_df))

Number of vehicles: 0

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
label_encoder = LabelEncoder()

In [49]:
df["origin_encoded"] = label_encoder.fit_transform(df["origin"])

In [50]:
df[["origin", "origin_encoded"]].drop_duplicates()

    origin  origin_encoded
0      usa               2
14   japan               1
19  europe               0

In [51]:
mapping = dict(zip(
    label_encoder.classes_,
    label_encoder.transform(label_encoder.classes_)
))

print(mapping)

{'europe': np.int64(0), 'japan': np.int64(1), 'usa': np.int64(2)}

In [52]:
one_hot = pd.get_dummies(df["origin"], prefix="origin")

In [53]:
one_hot.head()

   origin_europe  origin_japan  origin_usa
0          False         False        True
1          False         False        True
2          False         False        True
3          False         False        True
4          False         False        True

In [54]:
df = pd.concat([df, one_hot], axis=1)

In [55]:
df.head()

,name,miles_per_gallon,cylinders,displacement,hp,weight_lbs,acceleration,year,origin,weight_kg,mpg_category,vehicle_age,origin_encoded,origin_europe,origin_japan,origin_usa
0,chevrolet chevelle malibu,18.0,8.0,307.0,130.0,3504.0,12.0,70,usa,1589.386368,Low,56,2,False,False,True
1,buick skylark 320,15.0,8.0,350.0,165.0,3693.0,11.5,70,usa,1675.115256,Low,56,2,False,False,True
2,plymouth satellite,18.0,8.0,318.0,150.0,3436.0,11.0,70,usa,1558.542112,Low,56,2,False,False,True
3,amc rebel sst,16.0,8.0,304.0,150.0,3433.0,12.0,70,usa,1557.181336,Low,56,2,False,False,True
4,ford torino,17.0,NaN,302.0,140.0,3449.0,10.5,70,usa,1564.438808,Low,56,2,False,False,True

In [56]:
from scipy.stats import zscore

In [57]:
numerical_columns = df.select_dtypes(include=np.number).columns

In [58]:
z_scores = np.abs(zscore(df[numerical_columns]))

In [59]:
z_score_df = pd.DataFrame(
    z_scores,
    columns=numerical_columns,
    index=df.index
)

In [60]:
outlier_count = (z_score_df > 3).sum()

print(outlier_count)

miles_per_gallon    0
cylinders           0
displacement        0
hp                  4
weight_lbs          0
acceleration        0
year                0
weight_kg           0
vehicle_age         0
origin_encoded      0
dtype: int64

In [61]:
outlier_rows = df[(z_score_df > 3).any(axis=1)]

outlier_rows

,name,miles_per_gallon,cylinders,displacement,hp,weight_lbs,acceleration,year,origin,weight_kg,mpg_category,vehicle_age,origin_encoded,origin_europe,origin_japan,origin_usa
6,chevrolet impala,14.0,8.0,454.0,220.0,NaN,9.0,70,usa,NaN,Low,56,2,False,False,True
13,buick estate wagon (sw),14.0,8.0,455.0,225.0,3086.0,10.0,70,usa,1399.784912,Low,56,2,False,False,True
95,buick electra 225 custom,12.0,8.0,455.0,225.0,4951.0,11.0,73,usa,2245.733992,Low,53,2,False,False,True
116,pontiac grand prix,16.0,8.0,400.0,230.0,4278.0,9.5,73,usa,1940.466576,Low,53,2,False,False,True

In [62]:
from sklearn.preprocessing import StandardScaler

In [63]:
scale_columns = [
    "miles_per_gallon",
    "cylinders",
    "displacement",
    "hp",
    "weight_lbs",
    "acceleration",
    "year",
    "weight_kg",
    "vehicle_age"
]

In [64]:
standard_scaler = StandardScaler()

In [65]:
df_standardized = df.copy()

df_standardized[scale_columns] = standard_scaler.fit_transform(
    df[scale_columns]
)

In [66]:
df_standardized[scale_columns].head()

,miles_per_gallon,cylinders,displacement,hp,weight_lbs,acceleration,year,weight_kg,vehicle_age
0,-0.706439,1.507879,1.089802,0.685653,0.638455,-1.296894,-1.627426,0.638455,1.627426
1,-1.090751,1.507879,1.502099,1.620005,0.862339,-1.478926,-1.627426,0.862339,1.627426
2,-0.706439,1.507879,1.195273,1.219568,0.557904,-1.660957,-1.627426,0.557904,1.627426
3,-0.962647,1.507879,1.061037,1.219568,0.554350,-1.296894,-1.627426,0.554350,1.627426
4,-0.834543,NaN,1.041860,0.952611,0.573303,-1.842989,-1.627426,0.573303,1.627426

In [67]:
print(df_standardized[scale_columns].mean())

miles_per_gallon    7.141133e-17
cylinders           2.158611e-16
displacement       -1.259190e-16
hp                 -2.856453e-16
weight_lbs         -1.614870e-16
acceleration       -6.655717e-16
year               -1.642461e-15
weight_kg           5.382900e-17
vehicle_age        -2.142340e-16
dtype: float64

In [68]:
print(df_standardized[scale_columns].std())

miles_per_gallon    1.001259
cylinders           1.001268
displacement        1.001268
hp                  1.001259
weight_lbs          1.001265
acceleration        1.001268
year                1.001259
weight_kg           1.001265
vehicle_age         1.001259
dtype: float64

In [69]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
minmax_scaler = MinMaxScaler()